## YAML Template.
---
# Configuración de la base de datos
database:
  default_driver: 
  drivers:
    mysql: 
      host: 
      user:
      pass:
      name: 
      port: 
      socket:
    sqlite3:
      file: 
    oracle:
      host: 
      user: 
      pass: 
      name: 
      port: 
      protocol: 
      motor: 

# Configuración del sitio
build:
  production: false
  name: Framework
  url: https://psistemas.ufpso.edu.co/pcontroli/
  controller_ini: home
  timezone: America/Bogota
  domain: ufpso.edu.co